server:
  port: 8080

spring:
  redis:
    port: 6379
    password: 123456
    host: 192.168.11.236
    lettuce:
      pool:
        max-active: 10
        max-idle: 1
        min-idle: 0
        max-wait: 500
      shutdown-timeout: 100ms