singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: 123456
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://192.168.11.236:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 10
  connectionMinimumIdleSize: 0
  connectionPoolSize: 10
  database: 0
  dnsMonitoringInterval: 5000
threads: 4
nettyThreads: 4
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: NIO